#define SR_DATA		1
#define SR_DATA_PORT	PORTD
#define SR_DATA_PIN	PIND
#define SR_DATA_DDR	DDRD

#define SR_STROBE	0
#define SR_STROBE_PORT	PORTD
#define SR_STROBE_PIN	PIND
#define SR_STROBE_DDR	DDRD

#define SR_CLK		2
#define SR_CLK_PORT	PORTD
#define SR_CLK_PIN	PIND
#define SR_CLK_DDR	DDRD

#define SR_PL	0
#define SR_PL_PORT	PORTD
#define SR_PL_PIN	PIND
#define SR_PL_DDR	DDRD

#define LED_PIN		1
#define LED_PIN_PORT	PORTD
#define LED_PIN_PIN	PIND
#define LED_PIN_DDR	DDRD

#define LED_SELECT	0
#define LED_SELECT_PORT	PORTD
#define LED_SELECT_PIN	PIND
#define LED_SELECT_DDR	DDRD
